--- #YAML:1.0
name: Image-Imlib2
version: 0.11
license: perl
distribution_type: module
requires:
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
