--- #YAML:1.0
name: Image-Imlib2
version: 0.12
license: perl
distribution_type: module
requires:
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Image::Imlib2:
    file: lib/Image/Imlib2.pm
    version: 0.12
generated_by: Module::Build version 0.19
